# Generated by Django 5.2.7 on 2025-11-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('contenido', models.TextField()),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fk_emisor', models.ForeignKey(blank=True, db_column='fk_emisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.personas')),
                ('fk_receptor', models.ForeignKey(blank=True, db_column='fk_receptor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memos_fk_receptor_set', to='users.personas')),
            ],
            options={
                'db_table': 'memos',
            },
        ),
        migrations.CreateModel(
            name='ArchivosAdjuntos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.TextField()),
                ('ruta_archivo', models.TextField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('fk_memo', models.ForeignKey(blank=True, db_column='fk_memo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memos.memos')),
            ],
            options={
                'db_table': 'archivos_adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Validaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fk_memo', models.ForeignKey(blank=True, db_column='fk_memo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memos.memos')),
                ('fk_status', models.ForeignKey(blank=True, db_column='fk_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memos.status')),
                ('fk_validador', models.ForeignKey(blank=True, db_column='fk_validador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.personas')),
            ],
            options={
                'db_table': 'validaciones',
            },
        ),
    ]
